// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrKoD9ESb4BnUYlYEqq052dNPBrHgU77M',
    appId: '1:82028830831:web:4f776b5d6175547744ad9a',
    messagingSenderId: '82028830831',
    projectId: 'my-notes-e8765',
    authDomain: 'my-notes-e8765.firebaseapp.com',
    storageBucket: 'my-notes-e8765.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiC_k0MgLF-dTo-hci1K05N_j6gos70Ac',
    appId: '1:82028830831:android:d9ca55bfd4f0a92944ad9a',
    messagingSenderId: '82028830831',
    projectId: 'my-notes-e8765',
    storageBucket: 'my-notes-e8765.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD34BKmGhEBePKMAwt8UMpKq9XA5iPTTCo',
    appId: '1:82028830831:ios:bc92f933d686d3c744ad9a',
    messagingSenderId: '82028830831',
    projectId: 'my-notes-e8765',
    storageBucket: 'my-notes-e8765.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD34BKmGhEBePKMAwt8UMpKq9XA5iPTTCo',
    appId: '1:82028830831:ios:4c9133b0f6f702c444ad9a',
    messagingSenderId: '82028830831',
    projectId: 'my-notes-e8765',
    storageBucket: 'my-notes-e8765.appspot.com',
    iosBundleId: 'com.example.myNotes.RunnerTests',
  );
}
